services:
  - type: web
    name: tu-aplicacion-symfony
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    autoDeploy: true
